eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
      
feign:
  httpclient:
    disable-ssl-validation: true
  client:
    config:
      default:
        connectionTimeout: 5000
        readTimeout: 3000
        loggerLevel: full      
okta:
  oauth2:
    issuer: https://dev-18709465.okta.com/oauth2/default
